name: Daily Commit

on:
  schedule:
    - cron: '15 4 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # ✅ allows push access

      - name: Commit step - 22f1001112@ds.study.iitm.ac.in
        run: |
          echo "TDSFU Daily run: $(date -u) TDSFU" >> daily-log.txt

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "22f1001112@ds.study.iitm.ac.in"
          git add daily-log.txt
          git commit -m "Auto commit at $(date -u)" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
